version: "3.7"
services:

  redis:
    image: redis:7
    container_name: "redis"
    env_file:
      .env

  app:
    container_name: "app"
    image: app
    build: ./
    ports:
      - ${API_PORT}:${API_PORT}
    command: uvicorn main:app --host 0.0.0.0 --port ${API_PORT} 
    env_file:
      .env
    volumes:
      - ./accounts:/accounts:rw
      - ./media:/media:rw               # Добавление тома для /media папки
      - ./output:/output:rw

  alembic:
    container_name: "alembic"
    image: app
    build: ./
    environment:
      - ALEMBIC_INI=alembic.ini
    depends_on:
      - app
    command: alembic upgrade head
    env_file:
      .env

  celery:
    container_name: "celery"
    image: app
    command: celery -A src.core.celery_tasks worker --loglevel=${LOG_LEVEL} --purge
    build: ./
    env_file:
      .env
    volumes:
      - ./accounts:/accounts:rw
      - ./media:/media:rw               # Добавление тома для /media папки
      - ./output:/output:rw

  db:
    image: postgres
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    env_file:
     .env
    ports:
      - '5433:5432'