"""add proxy and account tables

Revision ID: 2da2cd88462b
Revises: 9445afa02886
Create Date: 2023-09-07 12:15:20.102762

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2da2cd88462b'
down_revision = '9445afa02886'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Proxies',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('addr', sa.String(), nullable=False),
    sa.Column('port', sa.Integer(), nullable=False),
    sa.Column('proxy_type', sa.Enum('HTTPS', 'SOCKS4', 'SOCKS5', name='proxytype'), nullable=False),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('password', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('addr')
    )
    op.create_table('Accounts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('login', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('requests', sa.Integer(), nullable=False),
    sa.Column('proxy_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['proxy_id'], ['Proxies.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('login')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Accounts')
    op.drop_table('Proxies')
    # ### end Alembic commands ###
