"""add reactions

Revision ID: 340ec0436975
Revises: 775ab6c4eef1
Create Date: 2025-03-04 13:53:15.645663

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '340ec0436975'
down_revision = '775ab6c4eef1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Posts', sa.Column('reactions', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Posts', 'reactions')
    # ### end Alembic commands ###
