"""add channel_name

Revision ID: 4800ed770670
Revises: 78aac51c4542
Create Date: 2025-03-04 15:36:33.383174

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4800ed770670'
down_revision = '78aac51c4542'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Posts', sa.Column('channel_name', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Posts', 'channel_name')
    # ### end Alembic commands ###
