"""add channel_id

Revision ID: 775ab6c4eef1
Revises: 4c68285d3545
Create Date: 2025-02-18 16:37:42.991532

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '775ab6c4eef1'
down_revision = '4c68285d3545'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Posts', sa.Column('channel_id', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Posts', 'channel_id')
    # ### end Alembic commands ###
