"""add reactions to db

Revision ID: 7022e145c4ef
Revises: c6e46d199f11
Create Date: 2023-04-18 01:27:52.337284

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "7022e145c4ef"
down_revision = "c6e46d199f11"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "parsing_results", sa.Column("reactions", sa.String(), nullable=False)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("parsing_results", "reactions")
    # ### end Alembic commands ###
