"""add requests counter

Revision ID: c4656fe9e496
Revises: 7022e145c4ef
Create Date: 2023-05-20 01:09:28.843455

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c4656fe9e496'
down_revision = '7022e145c4ef'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('accounts', sa.Column('requests', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('accounts', 'requests')
    # ### end Alembic commands ###
